version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: docker
      # You can use whatever password you like
      MYSQL_PASSWORD: docker
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    container_name: test_db
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    tty: true
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted on the local host
    volumes:
      - my-db:/var/lib/mysql
      - ./test.sql:/docker-entrypoint-initdb.d/0_init.sql
  app:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    environment: 
      PMA_HOST: db
# Names our volume
volumes:
  my-db: